run:
  deadline: 2m
linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - funlen
    - godox
    - gocyclo # is deprecated in favor of gocognit
linters-settings:
  lll:
    line-length: 180
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - lll
  max-issues-per-linter: 0
  max-same-issues: 0